# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_exchange(object):
    def setupUi(self, exchange):
        exchange.setObjectName("exchange")
        exchange.resize(1369, 686)
        self.pushButton = QtWidgets.QPushButton(exchange)
        self.pushButton.setGeometry(QtCore.QRect(820, 240, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(exchange)
        self.groupBox.setGeometry(QtCore.QRect(809, 20, 251, 241))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(exchange)
        self.groupBox_2.setGeometry(QtCore.QRect(140, 20, 641, 241))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.getUnderlyingDetailButton = QtWidgets.QPushButton(self.groupBox_2)
        self.getUnderlyingDetailButton.setGeometry(QtCore.QRect(10, 140, 81, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setItalic(False)
        self.getUnderlyingDetailButton.setFont(font)
        self.getUnderlyingDetailButton.setCheckable(False)
        self.getUnderlyingDetailButton.setFlat(False)
        self.getUnderlyingDetailButton.setObjectName("getUnderlyingDetailButton")
        self.widget = QtWidgets.QWidget(exchange)
        self.widget.setGeometry(QtCore.QRect(450, 50, 331, 152))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.impliedVol = QtWidgets.QLineEdit(self.widget)
        self.impliedVol.setText("")
        self.impliedVol.setReadOnly(True)
        self.impliedVol.setObjectName("impliedVol")
        self.gridLayout.addWidget(self.impliedVol, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.lb_symbol_6 = QtWidgets.QLabel(self.widget)
        self.lb_symbol_6.setObjectName("lb_symbol_6")
        self.gridLayout.addWidget(self.lb_symbol_6, 0, 2, 1, 1)
        self.lb_symbol_5 = QtWidgets.QLabel(self.widget)
        self.lb_symbol_5.setObjectName("lb_symbol_5")
        self.gridLayout.addWidget(self.lb_symbol_5, 0, 0, 1, 1)
        self.callOpenInterest = QtWidgets.QLineEdit(self.widget)
        self.callOpenInterest.setText("")
        self.callOpenInterest.setReadOnly(True)
        self.callOpenInterest.setObjectName("callOpenInterest")
        self.gridLayout.addWidget(self.callOpenInterest, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.stockLast = QtWidgets.QLineEdit(self.widget)
        self.stockLast.setText("")
        self.stockLast.setReadOnly(True)
        self.stockLast.setObjectName("stockLast")
        self.gridLayout.addWidget(self.stockLast, 0, 1, 1, 1)
        self.stockClose = QtWidgets.QLineEdit(self.widget)
        self.stockClose.setText("")
        self.stockClose.setReadOnly(True)
        self.stockClose.setObjectName("stockClose")
        self.gridLayout.addWidget(self.stockClose, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.putOpenInterest = QtWidgets.QLineEdit(self.widget)
        self.putOpenInterest.setText("")
        self.putOpenInterest.setReadOnly(True)
        self.putOpenInterest.setObjectName("putOpenInterest")
        self.gridLayout.addWidget(self.putOpenInterest, 1, 3, 1, 1)
        self.totalOpenInterest = QtWidgets.QLineEdit(self.widget)
        self.totalOpenInterest.setText("")
        self.totalOpenInterest.setReadOnly(True)
        self.totalOpenInterest.setObjectName("totalOpenInterest")
        self.gridLayout.addWidget(self.totalOpenInterest, 3, 3, 1, 1)
        self.daysFromExpiry = QtWidgets.QLineEdit(self.widget)
        self.daysFromExpiry.setText("")
        self.daysFromExpiry.setReadOnly(True)
        self.daysFromExpiry.setObjectName("daysFromExpiry")
        self.gridLayout.addWidget(self.daysFromExpiry, 5, 1, 1, 1)
        self.labelExpiry_4 = QtWidgets.QLabel(self.widget)
        self.labelExpiry_4.setObjectName("labelExpiry_4")
        self.gridLayout.addWidget(self.labelExpiry_4, 5, 0, 1, 1)
        self.lb_symbol_7 = QtWidgets.QLabel(self.widget)
        self.lb_symbol_7.setObjectName("lb_symbol_7")
        self.gridLayout.addWidget(self.lb_symbol_7, 4, 2, 1, 1)
        self.historicVol = QtWidgets.QLineEdit(self.widget)
        self.historicVol.setText("")
        self.historicVol.setReadOnly(True)
        self.historicVol.setObjectName("historicVol")
        self.gridLayout.addWidget(self.historicVol, 4, 1, 1, 1)
        self.labelExpiry_2 = QtWidgets.QLabel(self.widget)
        self.labelExpiry_2.setObjectName("labelExpiry_2")
        self.gridLayout.addWidget(self.labelExpiry_2, 4, 0, 1, 1)
        self.putVolume = QtWidgets.QLineEdit(self.widget)
        self.putVolume.setText("")
        self.putVolume.setReadOnly(True)
        self.putVolume.setObjectName("putVolume")
        self.gridLayout.addWidget(self.putVolume, 5, 3, 1, 1)
        self.callVolume = QtWidgets.QLineEdit(self.widget)
        self.callVolume.setText("")
        self.callVolume.setReadOnly(True)
        self.callVolume.setObjectName("callVolume")
        self.gridLayout.addWidget(self.callVolume, 4, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 2, 1, 1)
        self.totalVolume = QtWidgets.QLineEdit(self.widget)
        self.totalVolume.setText("")
        self.totalVolume.setReadOnly(True)
        self.totalVolume.setObjectName("totalVolume")
        self.gridLayout.addWidget(self.totalVolume, 6, 3, 1, 1)
        self.widget1 = QtWidgets.QWidget(exchange)
        self.widget1.setGeometry(QtCore.QRect(150, 50, 291, 101))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_expiry = QtWidgets.QLabel(self.widget1)
        self.lb_expiry.setObjectName("lb_expiry")
        self.gridLayout_2.addWidget(self.lb_expiry, 3, 0, 1, 1)
        self.dateExpiry = QtWidgets.QDateEdit(self.widget1)
        self.dateExpiry.setObjectName("dateExpiry")
        self.gridLayout_2.addWidget(self.dateExpiry, 3, 1, 1, 1)
        self.strike = QtWidgets.QLineEdit(self.widget1)
        self.strike.setText("")
        self.strike.setObjectName("strike")
        self.gridLayout_2.addWidget(self.strike, 0, 3, 1, 1)
        self.lb_SecType = QtWidgets.QLabel(self.widget1)
        self.lb_SecType.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_SecType.setObjectName("lb_SecType")
        self.gridLayout_2.addWidget(self.lb_SecType, 1, 0, 1, 1)
        self.lb_stk = QtWidgets.QLabel(self.widget1)
        self.lb_stk.setObjectName("lb_stk")
        self.gridLayout_2.addWidget(self.lb_stk, 0, 2, 1, 1)
        self.lb_callPut = QtWidgets.QLabel(self.widget1)
        self.lb_callPut.setObjectName("lb_callPut")
        self.gridLayout_2.addWidget(self.lb_callPut, 1, 2, 1, 1)
        self.call_put = QtWidgets.QLineEdit(self.widget1)
        self.call_put.setText("")
        self.call_put.setObjectName("call_put")
        self.gridLayout_2.addWidget(self.call_put, 1, 3, 1, 1)
        self.lb_symbol = QtWidgets.QLabel(self.widget1)
        self.lb_symbol.setObjectName("lb_symbol")
        self.gridLayout_2.addWidget(self.lb_symbol, 0, 0, 1, 1)
        self.lb_exc = QtWidgets.QLabel(self.widget1)
        self.lb_exc.setObjectName("lb_exc")
        self.gridLayout_2.addWidget(self.lb_exc, 2, 0, 1, 1)
        self.currency = QtWidgets.QLineEdit(self.widget1)
        self.currency.setText("")
        self.currency.setObjectName("currency")
        self.gridLayout_2.addWidget(self.currency, 2, 3, 1, 1)
        self.lb_currency = QtWidgets.QLabel(self.widget1)
        self.lb_currency.setObjectName("lb_currency")
        self.gridLayout_2.addWidget(self.lb_currency, 2, 2, 1, 1)
        self.symbol = QtWidgets.QLineEdit(self.widget1)
        self.symbol.setText("")
        self.symbol.setObjectName("symbol")
        self.gridLayout_2.addWidget(self.symbol, 0, 1, 1, 1)
        self.securityType = QtWidgets.QComboBox(self.widget1)
        self.securityType.setMaxCount(10)
        self.securityType.setObjectName("securityType")
        self.gridLayout_2.addWidget(self.securityType, 1, 1, 1, 1)
        self.exchange_2 = QtWidgets.QComboBox(self.widget1)
        self.exchange_2.setMaxCount(10)
        self.exchange_2.setObjectName("exchange_2")
        self.gridLayout_2.addWidget(self.exchange_2, 2, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(exchange)
        self.widget2.setGeometry(QtCore.QRect(820, 50, 241, 181))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rangeUSD_45Days = QtWidgets.QLineEdit(self.widget2)
        self.rangeUSD_45Days.setText("")
        self.rangeUSD_45Days.setReadOnly(True)
        self.rangeUSD_45Days.setObjectName("rangeUSD_45Days")
        self.gridLayout_3.addWidget(self.rangeUSD_45Days, 4, 2, 1, 1)
        self.maxDaysSpinBox = QtWidgets.QSpinBox(self.widget2)
        self.maxDaysSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.maxDaysSpinBox.setMinimum(20)
        self.maxDaysSpinBox.setMaximum(50)
        self.maxDaysSpinBox.setProperty("value", 45)
        self.maxDaysSpinBox.setObjectName("maxDaysSpinBox")
        self.gridLayout_3.addWidget(self.maxDaysSpinBox, 0, 2, 1, 1)
        self.minDaysSpinBox = QtWidgets.QSpinBox(self.widget2)
        self.minDaysSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.minDaysSpinBox.setMinimum(20)
        self.minDaysSpinBox.setMaximum(50)
        self.minDaysSpinBox.setProperty("value", 35)
        self.minDaysSpinBox.setObjectName("minDaysSpinBox")
        self.gridLayout_3.addWidget(self.minDaysSpinBox, 0, 1, 1, 1)
        self.rangeUSD_30Days = QtWidgets.QLineEdit(self.widget2)
        self.rangeUSD_30Days.setText("")
        self.rangeUSD_30Days.setReadOnly(True)
        self.rangeUSD_30Days.setObjectName("rangeUSD_30Days")
        self.gridLayout_3.addWidget(self.rangeUSD_30Days, 4, 1, 1, 1)
        self.rangePercent_30Days = QtWidgets.QLineEdit(self.widget2)
        self.rangePercent_30Days.setText("")
        self.rangePercent_30Days.setReadOnly(True)
        self.rangePercent_30Days.setObjectName("rangePercent_30Days")
        self.gridLayout_3.addWidget(self.rangePercent_30Days, 3, 1, 1, 1)
        self.lb_symbol_2 = QtWidgets.QLabel(self.widget2)
        self.lb_symbol_2.setObjectName("lb_symbol_2")
        self.gridLayout_3.addWidget(self.lb_symbol_2, 1, 0, 1, 1)
        self.volUSD_45Days = QtWidgets.QLineEdit(self.widget2)
        self.volUSD_45Days.setText("")
        self.volUSD_45Days.setReadOnly(True)
        self.volUSD_45Days.setObjectName("volUSD_45Days")
        self.gridLayout_3.addWidget(self.volUSD_45Days, 2, 2, 1, 1)
        self.lb_range3 = QtWidgets.QLabel(self.widget2)
        self.lb_range3.setObjectName("lb_range3")
        self.gridLayout_3.addWidget(self.lb_range3, 4, 0, 1, 1)
        self.rangePercent_45Days = QtWidgets.QLineEdit(self.widget2)
        self.rangePercent_45Days.setText("")
        self.rangePercent_45Days.setReadOnly(True)
        self.rangePercent_45Days.setObjectName("rangePercent_45Days")
        self.gridLayout_3.addWidget(self.rangePercent_45Days, 3, 2, 1, 1)
        self.volUSD_30Days = QtWidgets.QLineEdit(self.widget2)
        self.volUSD_30Days.setText("")
        self.volUSD_30Days.setReadOnly(True)
        self.volUSD_30Days.setObjectName("volUSD_30Days")
        self.gridLayout_3.addWidget(self.volUSD_30Days, 2, 1, 1, 1)
        self.volPercent_30Days = QtWidgets.QLineEdit(self.widget2)
        self.volPercent_30Days.setText("")
        self.volPercent_30Days.setReadOnly(True)
        self.volPercent_30Days.setObjectName("volPercent_30Days")
        self.gridLayout_3.addWidget(self.volPercent_30Days, 1, 1, 1, 1)
        self.lb_range4 = QtWidgets.QLabel(self.widget2)
        self.lb_range4.setObjectName("lb_range4")
        self.gridLayout_3.addWidget(self.lb_range4, 3, 0, 1, 1)
        self.lb_VolUSD = QtWidgets.QLabel(self.widget2)
        self.lb_VolUSD.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_VolUSD.setObjectName("lb_VolUSD")
        self.gridLayout_3.addWidget(self.lb_VolUSD, 2, 0, 1, 1)
        self.volPercent_45Days = QtWidgets.QLineEdit(self.widget2)
        self.volPercent_45Days.setText("")
        self.volPercent_45Days.setReadOnly(True)
        self.volPercent_45Days.setObjectName("volPercent_45Days")
        self.gridLayout_3.addWidget(self.volPercent_45Days, 1, 2, 1, 1)
        self.rangeUSD_up_30Days = QtWidgets.QLineEdit(self.widget2)
        self.rangeUSD_up_30Days.setText("")
        self.rangeUSD_up_30Days.setReadOnly(True)
        self.rangeUSD_up_30Days.setObjectName("rangeUSD_up_30Days")
        self.gridLayout_3.addWidget(self.rangeUSD_up_30Days, 6, 1, 1, 1)
        self.lb_range2 = QtWidgets.QLabel(self.widget2)
        self.lb_range2.setObjectName("lb_range2")
        self.gridLayout_3.addWidget(self.lb_range2, 6, 0, 1, 1)
        self.lb_range1 = QtWidgets.QLabel(self.widget2)
        self.lb_range1.setObjectName("lb_range1")
        self.gridLayout_3.addWidget(self.lb_range1, 7, 0, 1, 1)
        self.rangeUSD_up_45Days = QtWidgets.QLineEdit(self.widget2)
        self.rangeUSD_up_45Days.setText("")
        self.rangeUSD_up_45Days.setReadOnly(True)
        self.rangeUSD_up_45Days.setObjectName("rangeUSD_up_45Days")
        self.gridLayout_3.addWidget(self.rangeUSD_up_45Days, 6, 2, 1, 1)
        self.rangeUSD_down_30Days = QtWidgets.QLineEdit(self.widget2)
        self.rangeUSD_down_30Days.setText("")
        self.rangeUSD_down_30Days.setReadOnly(True)
        self.rangeUSD_down_30Days.setObjectName("rangeUSD_down_30Days")
        self.gridLayout_3.addWidget(self.rangeUSD_down_30Days, 7, 1, 1, 1)
        self.rangeUSD_down_45Days = QtWidgets.QLineEdit(self.widget2)
        self.rangeUSD_down_45Days.setText("")
        self.rangeUSD_down_45Days.setReadOnly(True)
        self.rangeUSD_down_45Days.setObjectName("rangeUSD_down_45Days")
        self.gridLayout_3.addWidget(self.rangeUSD_down_45Days, 7, 2, 1, 1)
        self.lb_symbol_3 = QtWidgets.QLabel(self.widget2)
        self.lb_symbol_3.setObjectName("lb_symbol_3")
        self.gridLayout_3.addWidget(self.lb_symbol_3, 0, 0, 1, 1)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.putVolume.raise_()
        self.callVolume.raise_()
        self.lb_symbol_7.raise_()
        self.label_8.raise_()
        self.lb_stk.raise_()
        self.pushButton.raise_()

        self.retranslateUi(exchange)
        QtCore.QMetaObject.connectSlotsByName(exchange)

    def retranslateUi(self, exchange):
        _translate = QtCore.QCoreApplication.translate
        exchange.setWindowTitle(_translate("exchange", "Dialog"))
        self.pushButton.setText(_translate("exchange", "Update Volatility"))
        self.groupBox.setTitle(_translate("exchange", "Projected Volatility"))
        self.groupBox_2.setTitle(_translate("exchange", "Underlying Detail"))
        self.getUnderlyingDetailButton.setText(_translate("exchange", "Get Details"))
        self.label_5.setText(_translate("exchange", "Implied Volatility"))
        self.label_7.setText(_translate("exchange", "Total Interest:"))
        self.lb_symbol_6.setText(_translate("exchange", "<html><head/><body><p>Call Open Interest</p></body></html>"))
        self.lb_symbol_5.setText(_translate("exchange", "Stock Last:"))
        self.label_6.setText(_translate("exchange", "<html><head/><body><p>Put Open Interest</p></body></html>"))
        self.label_3.setText(_translate("exchange", "Stock Close:"))
        self.labelExpiry_4.setText(_translate("exchange", "<html><head/><body><p>Days from Expiry:</p></body></html>"))
        self.lb_symbol_7.setText(_translate("exchange", "Call Volume"))
        self.labelExpiry_2.setText(_translate("exchange", "<html><head/><body><p>Historic Volitility</p></body></html>"))
        self.label_8.setText(_translate("exchange", "Put Volume"))
        self.label_9.setText(_translate("exchange", "Total Volume::"))
        self.lb_expiry.setText(_translate("exchange", "<html><head/><body><p>Option Expiry:</p></body></html>"))
        self.lb_SecType.setText(_translate("exchange", "Security Type:"))
        self.lb_stk.setText(_translate("exchange", "Strike"))
        self.lb_callPut.setText(_translate("exchange", "Call/Put"))
        self.lb_symbol.setText(_translate("exchange", "Symbol:"))
        self.lb_exc.setText(_translate("exchange", "Exchange:"))
        self.lb_currency.setText(_translate("exchange", "Currency"))
        self.lb_symbol_2.setText(_translate("exchange", "Volitility %"))
        self.lb_range3.setText(_translate("exchange", "<html><head/><body><p>$ Range +/-</p></body></html>"))
        self.lb_range4.setText(_translate("exchange", "% Range +/-"))
        self.lb_VolUSD.setText(_translate("exchange", "Volatility USD$"))
        self.lb_range2.setText(_translate("exchange", "<html><head/><body><p>$ Range (+) up</p></body></html>"))
        self.lb_range1.setText(_translate("exchange", "<html><head/><body><p>$ Range (-) down</p></body></html>"))
        self.lb_symbol_3.setText(_translate("exchange", "Min/Max day Range"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    exchange = QtWidgets.QDialog()
    ui = Ui_exchange()
    ui.setupUi(exchange)
    exchange.show()
    sys.exit(app.exec_())

