# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(300, 55, 401, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(760, 80, 241, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rangeUSD_45Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangeUSD_45Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangeUSD_45Days.setText("")
        self.rangeUSD_45Days.setReadOnly(True)
        self.rangeUSD_45Days.setObjectName("rangeUSD_45Days")
        self.gridLayout_3.addWidget(self.rangeUSD_45Days, 4, 2, 1, 1)
        self.maxDaysSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.maxDaysSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.maxDaysSpinBox.setMinimum(20)
        self.maxDaysSpinBox.setMaximum(50)
        self.maxDaysSpinBox.setProperty("value", 45)
        self.maxDaysSpinBox.setObjectName("maxDaysSpinBox")
        self.gridLayout_3.addWidget(self.maxDaysSpinBox, 0, 2, 1, 1)
        self.minDaysSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.minDaysSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.minDaysSpinBox.setMinimum(20)
        self.minDaysSpinBox.setMaximum(50)
        self.minDaysSpinBox.setProperty("value", 35)
        self.minDaysSpinBox.setObjectName("minDaysSpinBox")
        self.gridLayout_3.addWidget(self.minDaysSpinBox, 0, 1, 1, 1)
        self.rangeUSD_30Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangeUSD_30Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangeUSD_30Days.setText("")
        self.rangeUSD_30Days.setReadOnly(True)
        self.rangeUSD_30Days.setObjectName("rangeUSD_30Days")
        self.gridLayout_3.addWidget(self.rangeUSD_30Days, 4, 1, 1, 1)
        self.rangePercent_30Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangePercent_30Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangePercent_30Days.setText("")
        self.rangePercent_30Days.setReadOnly(True)
        self.rangePercent_30Days.setObjectName("rangePercent_30Days")
        self.gridLayout_3.addWidget(self.rangePercent_30Days, 3, 1, 1, 1)
        self.lb_volPerc = QtWidgets.QLabel(self.layoutWidget)
        self.lb_volPerc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_volPerc.setObjectName("lb_volPerc")
        self.gridLayout_3.addWidget(self.lb_volPerc, 1, 0, 1, 1)
        self.volUSD_45Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.volUSD_45Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.volUSD_45Days.setText("")
        self.volUSD_45Days.setReadOnly(True)
        self.volUSD_45Days.setObjectName("volUSD_45Days")
        self.gridLayout_3.addWidget(self.volUSD_45Days, 2, 2, 1, 1)
        self.lb_rangeUSD = QtWidgets.QLabel(self.layoutWidget)
        self.lb_rangeUSD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_rangeUSD.setObjectName("lb_rangeUSD")
        self.gridLayout_3.addWidget(self.lb_rangeUSD, 4, 0, 1, 1)
        self.rangePercent_45Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangePercent_45Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangePercent_45Days.setText("")
        self.rangePercent_45Days.setReadOnly(True)
        self.rangePercent_45Days.setObjectName("rangePercent_45Days")
        self.gridLayout_3.addWidget(self.rangePercent_45Days, 3, 2, 1, 1)
        self.volUSD_30Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.volUSD_30Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.volUSD_30Days.setText("")
        self.volUSD_30Days.setReadOnly(True)
        self.volUSD_30Days.setObjectName("volUSD_30Days")
        self.gridLayout_3.addWidget(self.volUSD_30Days, 2, 1, 1, 1)
        self.volPercent_30Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.volPercent_30Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.volPercent_30Days.setText("")
        self.volPercent_30Days.setReadOnly(True)
        self.volPercent_30Days.setObjectName("volPercent_30Days")
        self.gridLayout_3.addWidget(self.volPercent_30Days, 1, 1, 1, 1)
        self.lb_rangePerc = QtWidgets.QLabel(self.layoutWidget)
        self.lb_rangePerc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_rangePerc.setObjectName("lb_rangePerc")
        self.gridLayout_3.addWidget(self.lb_rangePerc, 3, 0, 1, 1)
        self.lb_VolUSD = QtWidgets.QLabel(self.layoutWidget)
        self.lb_VolUSD.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_VolUSD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_VolUSD.setObjectName("lb_VolUSD")
        self.gridLayout_3.addWidget(self.lb_VolUSD, 2, 0, 1, 1)
        self.volPercent_45Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.volPercent_45Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.volPercent_45Days.setText("")
        self.volPercent_45Days.setReadOnly(True)
        self.volPercent_45Days.setObjectName("volPercent_45Days")
        self.gridLayout_3.addWidget(self.volPercent_45Days, 1, 2, 1, 1)
        self.rangeUSD_up_30Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangeUSD_up_30Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangeUSD_up_30Days.setText("")
        self.rangeUSD_up_30Days.setReadOnly(True)
        self.rangeUSD_up_30Days.setObjectName("rangeUSD_up_30Days")
        self.gridLayout_3.addWidget(self.rangeUSD_up_30Days, 6, 1, 1, 1)
        self.lb_rangeUp = QtWidgets.QLabel(self.layoutWidget)
        self.lb_rangeUp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_rangeUp.setObjectName("lb_rangeUp")
        self.gridLayout_3.addWidget(self.lb_rangeUp, 6, 0, 1, 1)
        self.lb_rangeDown = QtWidgets.QLabel(self.layoutWidget)
        self.lb_rangeDown.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_rangeDown.setObjectName("lb_rangeDown")
        self.gridLayout_3.addWidget(self.lb_rangeDown, 7, 0, 1, 1)
        self.rangeUSD_up_45Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangeUSD_up_45Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangeUSD_up_45Days.setText("")
        self.rangeUSD_up_45Days.setReadOnly(True)
        self.rangeUSD_up_45Days.setObjectName("rangeUSD_up_45Days")
        self.gridLayout_3.addWidget(self.rangeUSD_up_45Days, 6, 2, 1, 1)
        self.rangeUSD_down_30Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangeUSD_down_30Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangeUSD_down_30Days.setText("")
        self.rangeUSD_down_30Days.setReadOnly(True)
        self.rangeUSD_down_30Days.setObjectName("rangeUSD_down_30Days")
        self.gridLayout_3.addWidget(self.rangeUSD_down_30Days, 7, 1, 1, 1)
        self.rangeUSD_down_45Days = QtWidgets.QLineEdit(self.layoutWidget)
        self.rangeUSD_down_45Days.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.rangeUSD_down_45Days.setText("")
        self.rangeUSD_down_45Days.setReadOnly(True)
        self.rangeUSD_down_45Days.setObjectName("rangeUSD_down_45Days")
        self.gridLayout_3.addWidget(self.rangeUSD_down_45Days, 7, 2, 1, 1)
        self.lb_MinMaxRg = QtWidgets.QLabel(self.layoutWidget)
        self.lb_MinMaxRg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_MinMaxRg.setObjectName("lb_MinMaxRg")
        self.gridLayout_3.addWidget(self.lb_MinMaxRg, 0, 0, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 80, 331, 158))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_ImpVol = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_ImpVol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_ImpVol.setObjectName("lb_ImpVol")
        self.gridLayout.addWidget(self.lb_ImpVol, 3, 0, 1, 1)
        self.impliedVol = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.impliedVol.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.impliedVol.setText("")
        self.impliedVol.setReadOnly(True)
        self.impliedVol.setObjectName("impliedVol")
        self.gridLayout.addWidget(self.impliedVol, 3, 1, 1, 1)
        self.lb_totalInt = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_totalInt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_totalInt.setObjectName("lb_totalInt")
        self.gridLayout.addWidget(self.lb_totalInt, 3, 2, 1, 1)
        self.lb_openInt = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_openInt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_openInt.setObjectName("lb_openInt")
        self.gridLayout.addWidget(self.lb_openInt, 0, 2, 1, 1)
        self.lb_stockLast = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_stockLast.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_stockLast.setObjectName("lb_stockLast")
        self.gridLayout.addWidget(self.lb_stockLast, 0, 0, 1, 1)
        self.callOpenInterest = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.callOpenInterest.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.callOpenInterest.setText("")
        self.callOpenInterest.setReadOnly(True)
        self.callOpenInterest.setObjectName("callOpenInterest")
        self.gridLayout.addWidget(self.callOpenInterest, 0, 3, 1, 1)
        self.lb_putCallInt = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_putCallInt.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_putCallInt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_putCallInt.setObjectName("lb_putCallInt")
        self.gridLayout.addWidget(self.lb_putCallInt, 1, 2, 1, 1)
        self.stockLast = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.stockLast.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.stockLast.setText("")
        self.stockLast.setReadOnly(True)
        self.stockLast.setObjectName("stockLast")
        self.gridLayout.addWidget(self.stockLast, 0, 1, 1, 1)
        self.stockClose = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.stockClose.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.stockClose.setText("")
        self.stockClose.setReadOnly(True)
        self.stockClose.setObjectName("stockClose")
        self.gridLayout.addWidget(self.stockClose, 1, 1, 1, 1)
        self.lb_stockClose = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_stockClose.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_stockClose.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_stockClose.setObjectName("lb_stockClose")
        self.gridLayout.addWidget(self.lb_stockClose, 1, 0, 1, 1)
        self.putOpenInterest = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.putOpenInterest.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.putOpenInterest.setText("")
        self.putOpenInterest.setReadOnly(True)
        self.putOpenInterest.setObjectName("putOpenInterest")
        self.gridLayout.addWidget(self.putOpenInterest, 1, 3, 1, 1)
        self.totalOpenInterest = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.totalOpenInterest.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.totalOpenInterest.setText("")
        self.totalOpenInterest.setReadOnly(True)
        self.totalOpenInterest.setObjectName("totalOpenInterest")
        self.gridLayout.addWidget(self.totalOpenInterest, 3, 3, 1, 1)
        self.daysFromExpiry = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.daysFromExpiry.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.daysFromExpiry.setText("")
        self.daysFromExpiry.setReadOnly(True)
        self.daysFromExpiry.setObjectName("daysFromExpiry")
        self.gridLayout.addWidget(self.daysFromExpiry, 5, 1, 1, 1)
        self.lb_Exp = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_Exp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Exp.setObjectName("lb_Exp")
        self.gridLayout.addWidget(self.lb_Exp, 5, 0, 1, 1)
        self.lb_callVol = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_callVol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_callVol.setObjectName("lb_callVol")
        self.gridLayout.addWidget(self.lb_callVol, 4, 2, 1, 1)
        self.historicVol = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.historicVol.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.historicVol.setText("")
        self.historicVol.setReadOnly(True)
        self.historicVol.setObjectName("historicVol")
        self.gridLayout.addWidget(self.historicVol, 4, 1, 1, 1)
        self.labelExpiry_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelExpiry_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelExpiry_2.setObjectName("labelExpiry_2")
        self.gridLayout.addWidget(self.labelExpiry_2, 4, 0, 1, 1)
        self.putVolume = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.putVolume.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.putVolume.setText("")
        self.putVolume.setReadOnly(True)
        self.putVolume.setObjectName("putVolume")
        self.gridLayout.addWidget(self.putVolume, 5, 3, 1, 1)
        self.callVolume = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.callVolume.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.callVolume.setText("")
        self.callVolume.setReadOnly(True)
        self.callVolume.setObjectName("callVolume")
        self.gridLayout.addWidget(self.callVolume, 4, 3, 1, 1)
        self.lb_putVol = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_putVol.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_putVol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_putVol.setObjectName("lb_putVol")
        self.gridLayout.addWidget(self.lb_putVol, 5, 2, 1, 1)
        self.lb_totalVol = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_totalVol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_totalVol.setObjectName("lb_totalVol")
        self.gridLayout.addWidget(self.lb_totalVol, 6, 2, 1, 1)
        self.totalVolume = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.totalVolume.setStyleSheet("background-color: rgb(202, 226, 163);")
        self.totalVolume.setText("")
        self.totalVolume.setReadOnly(True)
        self.totalVolume.setObjectName("totalVolume")
        self.gridLayout.addWidget(self.totalVolume, 6, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(980, 50, 31, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(80, 80, 291, 126))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_expiry = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_expiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_expiry.setObjectName("lb_expiry")
        self.gridLayout_2.addWidget(self.lb_expiry, 3, 0, 1, 1)
        self.lb_SecType = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_SecType.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_SecType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_SecType.setObjectName("lb_SecType")
        self.gridLayout_2.addWidget(self.lb_SecType, 1, 0, 1, 1)
        self.lb_symbol = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_symbol.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lb_symbol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_symbol.setObjectName("lb_symbol")
        self.gridLayout_2.addWidget(self.lb_symbol, 0, 0, 1, 1)
        self.strike = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.strike.setText("")
        self.strike.setObjectName("strike")
        self.gridLayout_2.addWidget(self.strike, 0, 3, 1, 1)
        self.securityType = QtWidgets.QComboBox(self.layoutWidget_3)
        self.securityType.setMaxCount(10)
        self.securityType.setObjectName("securityType")
        self.gridLayout_2.addWidget(self.securityType, 1, 1, 1, 1)
        self.exchangeLoc = QtWidgets.QComboBox(self.layoutWidget_3)
        self.exchangeLoc.setMaxCount(10)
        self.exchangeLoc.setObjectName("exchangeLoc")
        self.gridLayout_2.addWidget(self.exchangeLoc, 2, 1, 1, 1)
        self.lb_exchange = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_exchange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_exchange.setObjectName("lb_exchange")
        self.gridLayout_2.addWidget(self.lb_exchange, 2, 0, 1, 1)
        self.dateExpiry = QtWidgets.QDateEdit(self.layoutWidget_3)
        self.dateExpiry.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(2, 0, 0)))
        self.dateExpiry.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 31), QtCore.QTime(12, 59, 59)))
        self.dateExpiry.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 9, 14), QtCore.QTime(2, 0, 0)))
        self.dateExpiry.setCalendarPopup(True)
        self.dateExpiry.setObjectName("dateExpiry")
        self.gridLayout_2.addWidget(self.dateExpiry, 3, 1, 1, 1)
        self.lb_callPut = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_callPut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_callPut.setObjectName("lb_callPut")
        self.gridLayout_2.addWidget(self.lb_callPut, 1, 2, 1, 1)
        self.lb_currency = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_currency.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_currency.setObjectName("lb_currency")
        self.gridLayout_2.addWidget(self.lb_currency, 2, 2, 1, 1)
        self.lb_stk = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_stk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_stk.setObjectName("lb_stk")
        self.gridLayout_2.addWidget(self.lb_stk, 0, 2, 1, 1)
        self.symbol = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.symbol.setInputMask("")
        self.symbol.setText("")
        self.symbol.setPlaceholderText("")
        self.symbol.setObjectName("symbol")
        self.gridLayout_2.addWidget(self.symbol, 0, 1, 1, 1)
        self.callPut = QtWidgets.QComboBox(self.layoutWidget_3)
        self.callPut.setObjectName("callPut")
        self.gridLayout_2.addWidget(self.callPut, 1, 3, 1, 1)
        self.currency = QtWidgets.QComboBox(self.layoutWidget_3)
        self.currency.setObjectName("currency")
        self.gridLayout_2.addWidget(self.currency, 2, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(720, 20, 20, 251))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setTearOffEnabled(True)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionconnectIB = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Pictures/Connect No.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionconnectIB.setIcon(icon)
        self.actionconnectIB.setObjectName("actionconnectIB")
        self.actionRefresh_Detail = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Pictures/Refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh_Detail.setIcon(icon1)
        self.actionRefresh_Detail.setObjectName("actionRefresh_Detail")
        self.actionVolatility = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Pictures/chart-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVolatility.setIcon(icon2)
        self.actionVolatility.setObjectName("actionVolatility")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../Pictures/Actions-application-exit-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.menubar.addAction(self.menuMenu.menuAction())
        self.toolBar.addAction(self.actionconnectIB)
        self.toolBar.addAction(self.actionRefresh_Detail)
        self.toolBar.addAction(self.actionVolatility)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.symbol, self.strike)
        MainWindow.setTabOrder(self.strike, self.securityType)
        MainWindow.setTabOrder(self.securityType, self.callPut)
        MainWindow.setTabOrder(self.callPut, self.exchangeLoc)
        MainWindow.setTabOrder(self.exchangeLoc, self.currency)
        MainWindow.setTabOrder(self.currency, self.dateExpiry)
        MainWindow.setTabOrder(self.dateExpiry, self.minDaysSpinBox)
        MainWindow.setTabOrder(self.minDaysSpinBox, self.maxDaysSpinBox)
        MainWindow.setTabOrder(self.maxDaysSpinBox, self.volUSD_45Days)
        MainWindow.setTabOrder(self.volUSD_45Days, self.rangeUSD_30Days)
        MainWindow.setTabOrder(self.rangeUSD_30Days, self.rangeUSD_45Days)
        MainWindow.setTabOrder(self.rangeUSD_45Days, self.rangePercent_30Days)
        MainWindow.setTabOrder(self.rangePercent_30Days, self.rangePercent_45Days)
        MainWindow.setTabOrder(self.rangePercent_45Days, self.volUSD_30Days)
        MainWindow.setTabOrder(self.volUSD_30Days, self.volPercent_30Days)
        MainWindow.setTabOrder(self.volPercent_30Days, self.volPercent_45Days)
        MainWindow.setTabOrder(self.volPercent_45Days, self.rangeUSD_up_30Days)
        MainWindow.setTabOrder(self.rangeUSD_up_30Days, self.rangeUSD_up_45Days)
        MainWindow.setTabOrder(self.rangeUSD_up_45Days, self.rangeUSD_down_30Days)
        MainWindow.setTabOrder(self.rangeUSD_down_30Days, self.rangeUSD_down_45Days)
        MainWindow.setTabOrder(self.rangeUSD_down_45Days, self.impliedVol)
        MainWindow.setTabOrder(self.impliedVol, self.callOpenInterest)
        MainWindow.setTabOrder(self.callOpenInterest, self.stockLast)
        MainWindow.setTabOrder(self.stockLast, self.stockClose)
        MainWindow.setTabOrder(self.stockClose, self.putOpenInterest)
        MainWindow.setTabOrder(self.putOpenInterest, self.totalOpenInterest)
        MainWindow.setTabOrder(self.totalOpenInterest, self.daysFromExpiry)
        MainWindow.setTabOrder(self.daysFromExpiry, self.historicVol)
        MainWindow.setTabOrder(self.historicVol, self.putVolume)
        MainWindow.setTabOrder(self.putVolume, self.callVolume)
        MainWindow.setTabOrder(self.callVolume, self.totalVolume)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Underlying Detail"))
        self.lb_volPerc.setText(_translate("MainWindow", "<html><head/><body><p>Volatility %</p></body></html>"))
        self.lb_rangeUSD.setText(_translate("MainWindow", "<html><head/><body><p>$ Range +/-</p></body></html>"))
        self.lb_rangePerc.setText(_translate("MainWindow", "% Range +/-"))
        self.lb_VolUSD.setText(_translate("MainWindow", "Volatility USD$"))
        self.lb_rangeUp.setText(_translate("MainWindow", "<html><head/><body><p>$ Range (+) up</p></body></html>"))
        self.lb_rangeDown.setText(_translate("MainWindow", "<html><head/><body><p>$ Range (-) down</p></body></html>"))
        self.lb_MinMaxRg.setText(_translate("MainWindow", "Min/Max Day Range"))
        self.lb_ImpVol.setText(_translate("MainWindow", "Implied Volatility:"))
        self.lb_totalInt.setText(_translate("MainWindow", "Total Interest:"))
        self.lb_openInt.setText(_translate("MainWindow", "Call Open Interest:"))
        self.lb_stockLast.setText(_translate("MainWindow", "Stock Last:"))
        self.lb_putCallInt.setText(_translate("MainWindow", "Put Open Interest:"))
        self.lb_stockClose.setText(_translate("MainWindow", "Stock Close:"))
        self.lb_Exp.setText(_translate("MainWindow", "Days from Expiry:"))
        self.lb_callVol.setText(_translate("MainWindow", "Call Volume:"))
        self.labelExpiry_2.setText(_translate("MainWindow", "Historic Volatility:"))
        self.lb_putVol.setText(_translate("MainWindow", "Put Volume:"))
        self.lb_totalVol.setText(_translate("MainWindow", "Total Volume:"))
        self.label_2.setText(_translate("MainWindow", "Projected Volatility"))
        self.lb_expiry.setText(_translate("MainWindow", "<html><head/><body><p>Option Expiry:</p></body></html>"))
        self.lb_SecType.setText(_translate("MainWindow", "Security Type:"))
        self.lb_symbol.setText(_translate("MainWindow", "Symbol:"))
        self.lb_exchange.setText(_translate("MainWindow", "Exchange:"))
        self.lb_callPut.setText(_translate("MainWindow", "Call/Put:"))
        self.lb_currency.setText(_translate("MainWindow", "Currency:"))
        self.lb_stk.setText(_translate("MainWindow", "Strike:"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionconnectIB.setText(_translate("MainWindow", "Connect to IB"))
        self.actionconnectIB.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">Connect to IB</span></p></body></html>"))
        self.actionconnectIB.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionRefresh_Detail.setText(_translate("MainWindow", "Refresh Detail"))
        self.actionRefresh_Detail.setToolTip(_translate("MainWindow", "Refresh Underlying Detail"))
        self.actionRefresh_Detail.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.actionVolatility.setText(_translate("MainWindow", "Volatility"))
        self.actionVolatility.setToolTip(_translate("MainWindow", "Get Projected Volatility"))
        self.actionVolatility.setShortcut(_translate("MainWindow", "Ctrl+Shift+V"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quit App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

